branch-defaults:
  default:
    environment: Sample-env
  master:
    environment: django-testenv3
    group_suffix: null
environment-defaults:
  Sample-env:
    branch: null
    repository: null
  django-env7:
    branch: master
    repository: site1
global:
  application_name: site1
  branch: null
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-west-1
  profile: eb-cli
  repository: null
  sc: git
